//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCSEND2.Properties
{
	using System;


	/// <summary>
	///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
	/// </summary>
	// このクラスは StronglyTypedResourceBuilder クラスが ResGen
	// または Visual Studio のようなツールを使用して自動生成されました。
	// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
	// ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCSEND2.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
		///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Icon BOOK02 {
			get {
				object obj = ResourceManager.GetObject("BOOK02", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap book2 {
			get {
				object obj = ResourceManager.GetObject("book2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap checkmark {
			get {
				object obj = ResourceManager.GetObject("checkmark", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Icon CHECKMRK {
			get {
				object obj = ResourceManager.GetObject("CHECKMRK", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap edit {
			get {
				object obj = ResourceManager.GetObject("edit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Icon EDIT1 {
			get {
				object obj = ResourceManager.GetObject("EDIT1", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap litening {
			get {
				object obj = ResourceManager.GetObject("litening", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Icon LITENING1 {
			get {
				object obj = ResourceManager.GetObject("LITENING1", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap refresh {
			get {
				object obj = ResourceManager.GetObject("refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Icon REFRESH1 {
			get {
				object obj = ResourceManager.GetObject("REFRESH1", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap table {
			get {
				object obj = ResourceManager.GetObject("table", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Icon TABLE1 {
			get {
				object obj = ResourceManager.GetObject("TABLE1", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}

		/// <summary>
		///   型 System.Byte[] のローカライズされたリソースを検索します。
		/// </summary>
		internal static byte[] 工程パラ_2_5D {
			get {
				object obj = ResourceManager.GetObject("工程パラ_2_5D", resourceCulture);
				return ((byte[])(obj));
			}
		}

		/// <summary>
		///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
		/// </summary>
		internal static System.Drawing.Bitmap 金型 {
			get {
				object obj = ResourceManager.GetObject("金型", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
